# Verify work from scripts is correct

## (1) data from youtube_collector.py

In [1]:
import pandas as pd 

# read in the csv generated from 10 test rows 
test_10 = pd.read_csv("../data/raw/metadata.csv")

# verify cols and count 
test_10.columns

# check that image data is usable
# image is jpg format 
test_10['thumbnail_url'].iloc[0]

count_rows = len(test_10)
print(count_rows)

# head check 
test_10.head(10)

50

,video_id,channel,publish_date,title,thumbnail_url,views,likes,comments
0,4yauPjEce8I,Loveneet Valecha,2025-12-30T10:52:33Z,Finally humare ghar bhi ban gaya😅 #cooking #fo...,https://i.ytimg.com/vi/4yauPjEce8I/hqdefault.jpg,304673799,2812599.0,4607.0
1,yh4nSLUR0So,Lưu Quang Minh Review,2026-03-30T04:08:51Z,Xúc Xích Nướng Giấy Bạc ngon tuyệt! #xucxich #...,https://i.ytimg.com/vi/yh4nSLUR0So/hqdefault.jpg,235,2.0,0.0
2,3VpWb7bK9cg,Daily Lici,2026-03-30T03:40:58Z,#pinbutton #alatpresspin #mesinpin #diy #tutorial,https://i.ytimg.com/vi/3VpWb7bK9cg/hqdefault.jpg,773,7.0,0.0
3,j8ZxI2no9gw,chop-ru,2025-06-30T09:10:00Z,Satisfying With Unboxing & Review Pink Mini Ki...,https://i.ytimg.com/vi/j8ZxI2no9gw/hqdefault.jpg,96131545,293541.0,60.0
4,DO5MflX_eik,Odysseas,2025-12-20T16:23:54Z,I’m begging you to write essays,https://i.ytimg.com/vi/DO5MflX_eik/hqdefault.jpg,1247285,84560.0,2181.0
5,0AxZM6TmoiM,Ángel soy yo,2025-09-14T00:05:49Z,Tutorial como comerte una espiropapa🥔corregido,https://i.ytimg.com/vi/0AxZM6TmoiM/hqdefault.jpg,152567895,2577476.0,7101.0
6,rB4ONN2Bolk,মেন্টাল সামিম,2026-03-30T04:03:45Z,সারাদিন বাড়ির বাহিরে 🏠 😜| #minivlog #vlog,https://i.ytimg.com/vi/rB4ONN2Bolk/hqdefault.jpg,491,4.0,0.0
7,6p4phB2Rybs,daily mind trap,2025-04-13T16:00:07Z,What’s Wrong With Eating Humans?,https://i.ytimg.com/vi/6p4phB2Rybs/hqdefault.jpg,1673469,92970.0,6794.0
8,thzpvP4Hseg,Poofy💨,2025-08-15T15:44:07Z,If you want a textured fringe do this,https://i.ytimg.com/vi/thzpvP4Hseg/hqdefault.jpg,184852752,2115356.0,14661.0
9,vBGd4COy8BY,FutbolEssence,2025-07-25T02:57:21Z,#effectking,https://i.ytimg.com/vi/vBGd4COy8BY/hqdefault.jpg,21528121,188842.0,1593.0

## (2) data from extract_features.py

In [8]:
features_df = pd.read_csv("../data/processed/features.csv")

features_df.columns

len(features_df)

features_df.head(10)

,video_id,edge_density,blur,corner_count,contrast,views,keypoint_count,colorfulness,brightness,entropy,text,text_length,text_count,text_presence,face_count,symmetry
0,4yauPjEce8I,0.094994,1496.311150,100,63.269951,304673799,500,94.351692,79.746094,5.130339,NaN,0,0,0,0,0.865550
1,yh4nSLUR0So,0.073125,963.166646,100,65.041044,235,500,100.519791,81.794792,5.034047,NaN,0,0,0,1,0.846746
2,3VpWb7bK9cg,0.074271,1316.639375,100,66.480626,773,500,125.531398,70.240284,4.999984,NaN,0,0,0,0,0.830964
3,j8ZxI2no9gw,0.049178,657.952125,100,70.540280,96131545,500,112.783676,96.309352,4.866308,NaN,0,0,0,0,0.908207
4,DO5MflX_eik,0.108657,2348.818194,100,92.109275,1247285,500,128.259639,94.476458,4.643154,NaN,0,0,0,3,0.701819
5,0AxZM6TmoiM,0.083027,1526.173478,100,58.050867,152567895,500,118.829623,66.956383,4.967712,NaN,0,0,0,1,0.861263
6,rB4ONN2Bolk,0.070509,881.745323,100,66.719330,491,500,102.114062,80.609931,4.846685,NaN,0,0,0,0,0.771294
7,6p4phB2Rybs,0.091192,1736.954502,100,77.630807,1673469,500,117.726401,101.942153,4.698981,NaN,0,0,0,1,0.887097
8,thzpvP4Hseg,0.040278,652.200437,100,60.614892,184852752,500,88.216446,70.676169,4.902709,NaN,0,0,0,0,0.895467
9,vBGd4COy8BY,0.030399,863.555894,100,48.555195,21528121,500,127.001237,56.510318,4.622511,NaN,0,0,0,1,0.902002